// @ts-check

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		'documentation/home',
		'documentation/quickstart',
		{
			type: 'category',
			label: 'Installation',
			link: {
				type: 'doc',
				id: 'documentation/installation/index',
			},
			items: [
				'documentation/installation/docker',
			],
		},
		{
			type: 'category',
			label: 'Guides',
			items: [
				'documentation/guides/user-guide',
			],
		},
		{
			type: 'category',
			label: 'System Reference',
			items: [
				'documentation/system-reference/architecture',
				'documentation/system-reference/data_model',
				{
					type: 'category',
					label: 'Services',
					link: {
						type: 'doc',
						id: 'documentation/system-reference/services/index',
					},
					items: [
						'documentation/system-reference/services/backoffice',
						{
							type: 'category',
							label: 'Converter',
							link: {
								type: 'doc',
								id: 'documentation/system-reference/services/converter/index',
							},
							items: [
								'documentation/system-reference/services/converter/plugins',
								'documentation/system-reference/services/converter/plugin-populator',
							],
						},
					],
				},
				{
					type: 'category',
					label: 'Data Formats',
					link: {
						type: 'doc',
						id: 'documentation/system-reference/data-formats/index',
					},
					items: [
						'documentation/system-reference/data-formats/dcat-ap',
						'documentation/system-reference/data-formats/geojson',
						{
							type: 'category',
							label: 'CoverageJSON',
							link: {
								type: 'doc',
								id: 'documentation/system-reference/data-formats/coveragejson/index',
							},
							items: [
								'documentation/system-reference/data-formats/coveragejson/error_bars',
								'documentation/system-reference/data-formats/coveragejson/scatter_plot_guide',
							],
						},
					],
				},
			],
		},
		'documentation/license',
	],
	contributorSidebar: [{ type: 'autogenerated', dirName: 'contributors' }],
};

export default sidebars;
